// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMd7YbAhomrdWKBl5S_8IVA6wL3tRPKw',
    appId: '1:243238946971:web:b0cb07c5642df63fd29e3e',
    messagingSenderId: '243238946971',
    projectId: 'testingbackend-c3cbc',
    authDomain: 'testingbackend-c3cbc.firebaseapp.com',
    storageBucket: 'testingbackend-c3cbc.firebasestorage.app',
    measurementId: 'G-PPJ56Z2D7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADhFmQHxgdpRwWkrTtuPbGxeWR2fW3j8U',
    appId: '1:243238946971:android:ebe93c1b31ce79f4d29e3e',
    messagingSenderId: '243238946971',
    projectId: 'testingbackend-c3cbc',
    storageBucket: 'testingbackend-c3cbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa2SOObwa2tMBgafXQpaARR5pcItvtlUA',
    appId: '1:243238946971:ios:fa24d6ca90c2ccc4d29e3e',
    messagingSenderId: '243238946971',
    projectId: 'testingbackend-c3cbc',
    storageBucket: 'testingbackend-c3cbc.firebasestorage.app',
    iosBundleId: 'com.example.eventosCruzDeCristal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfakeMacosApiKey12345',
    appId: '1:123456789012:macos:fakeid',
    messagingSenderId: '123456789012',
    projectId: 'eventos-cruz-de-cristal',
    storageBucket: 'eventos-cruz-de-cristal.appspot.com',
    iosBundleId: 'com.example.eventosCruzDeCristal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfakeWindowsApiKey12345',
    appId: '1:123456789012:windows:fakeid',
    messagingSenderId: '123456789012',
    projectId: 'eventos-cruz-de-cristal',
  );
} 